-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 17:45:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_portifolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_portifolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_portifolio` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_portifolio` ;

-- -----------------------------------------------------
-- Table `db_portifolio`.`tb_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_portifolio`.`tb_admin` (
  `cd_admin` INT NOT NULL AUTO_INCREMENT,
  `cd_senha` TEXT NOT NULL,
  `cd_caminho_curriculo` VARCHAR(200) NOT NULL,
  `cd_caminho_pfp` VARCHAR(200) NOT NULL,
  `lk_github` VARCHAR(100) NOT NULL,
  `lk_linkedin` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cd_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portifolio`.`tb_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_portifolio`.`tb_projeto` (
  `cd_projeto` INT NOT NULL AUTO_INCREMENT,
  `nm_projeto` VARCHAR(70) NOT NULL,
  `ds_descricao` LONGTEXT NOT NULL,
  `lk_github` VARCHAR(100) NULL,
  `lk_expo` VARCHAR(100) NULL,
  `lk_online` VARCHAR(100) NULL,
  PRIMARY KEY (`cd_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portifolio`.`tb_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_portifolio`.`tb_imagem` (
  `cd_imagem` INT NOT NULL AUTO_INCREMENT,
  `nm_caminho` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cd_imagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_portifolio`.`tb_imagem_tb_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_portifolio`.`tb_imagem_tb_projeto` (
  `id_imagem` INT NOT NULL,
  `id_projeto` INT NOT NULL,
  PRIMARY KEY (`id_imagem`, `id_projeto`),
  CONSTRAINT `fk_tb_imagem_has_tb_projeto_tb_imagem`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `db_portifolio`.`tb_imagem` (`cd_imagem`),
  CONSTRAINT `fk_tb_imagem_has_tb_projeto_tb_projeto1`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `db_portifolio`.`tb_projeto` (`cd_projeto`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
